name: Release

on:
  push:
    tags:
      - 'v*.*.*' # runs on version tags like v1.2.3

permissions:
  contents: write # needed for creating GitHub releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_HOMEBREW_GITHUB_TOKEN: ${{ secrets.GORELEASER_HOMEBREW_GITHUB_TOKEN }}
